[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
youbet_solana_program = "CuuiWq1ATi8XUgnv8tdiYNQKccs3iNw2uz9CDAZeuc15"

[programs.localnet]
youbet_solana_program = "CuuiWq1ATi8XUgnv8tdiYNQKccs3iNw2uz9CDAZeuc15"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "Devnet"
wallet = "~/.config/solana/cli/validator-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
